package com.hyzer.early;

import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import static com.hyzer.early.EarlyLogger.*;

/**
 * ASM ClassVisitor for CommandBuffer transformation.
 * Intercepts the lambda$removeComponent$0 method to change removeComponent to tryRemoveComponent.
 */
public class CommandBufferVisitor extends ClassVisitor {

    private String className;

    // The lambda method generated by the compiler for removeComponent()
    // From stack trace: CommandBuffer.lambda$removeComponent$0(CommandBuffer.java:430)
    private static final String LAMBDA_METHOD_PREFIX = "lambda$removeComponent$";

    public CommandBufferVisitor(ClassVisitor cv) {
        super(Opcodes.ASM9, cv);
    }

    @Override
    public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
        this.className = name;
        super.visit(version, access, name, signature, superName, interfaces);
    }

    @Override
    public MethodVisitor visitMethod(int access, String name, String descriptor, String signature, String[] exceptions) {
        MethodVisitor mv = super.visitMethod(access, name, descriptor, signature, exceptions);

        // Look for lambda$removeComponent$ methods (there could be multiple with different indices)
        if (name.startsWith(LAMBDA_METHOD_PREFIX)) {
            verbose("Found lambda method: " + name + descriptor);
            verbose("Transforming to use tryRemoveComponent instead of removeComponent...");
            return new RemoveComponentLambdaMethodVisitor(mv, className, name);
        }

        return mv;
    }
}
